name: Org Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */6 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.KEY }}
          # Options
          filename: org-metrics.svg
          user: catgirls-top
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Prague
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_visibility: all
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_ignored: html,c++,css,cmake,c
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_languages_threshold: 2%
          plugin_languages_indepth: yes
          plugin_lines: yes
          plugin_traffic: yes
