# OsuCard action test

name: OsuCard

# Controls when the action will run. 
on:
 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: OsuCard
        uses: catgirls-top/OsuCard@main
        with:
          osu-name: hernik
          client-id: a
          client-secret: b
